name: oqc_registro_salidas
description: App de escritorio para registro de salidas OQC - Ilsan Electronics
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  data_table_2: ^2.5.8
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  window_manager: ^0.3.7
  archive: ^3.4.9
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/ImagenLogo1.png"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/images/
